package models

import "strings"

// ChainAliasToName maps every supported chain alias to its canonical lowercase chain name.
var ChainAliasToName = map[string]string{
	// XDAI
	"xdai":           "xdai",
	"gnosis":         "xdai",
	"gnosis-chain":   "xdai",
	"gnosischain":    "xdai",
	"gnosis-mainnet": "xdai",
	// ETH
	"eth":              "eth",
	"ethereum":         "eth",
	"mainnet":          "eth",
	"ethereum-mainnet": "eth",
	// STRK
	"strk":             "strk",
	"starknet":         "strk",
	"starknet-mainnet": "strk",
	// METIS
	"metis":           "metis",
	"metis-andromeda": "metis",
	"metisandromeda":  "metis",
	"metis-mainnet":   "metis",
	// FRAX
	"frax":            "frax",
	"fraxtal":         "frax",
	"fraxtal-mainnet": "frax",
	// WEMIX
	"wemix":         "wemix",
	"wemix3":        "wemix",
	"wemix3.0":      "wemix",
	"wemix-mainnet": "wemix",
	// APT
	"apt":           "apt",
	"aptos":         "apt",
	"aptos-mainnet": "apt",
	// RON
	"ron":           "ron",
	"ronin":         "ron",
	"ronin-mainnet": "ron",
	// BERA
	"bera":             "bera",
	"berachain":        "bera",
	"bera-testnet":     "bera",
	"berachain-bartio": "bera",
	// NEON
	"neon":         "neon",
	"neon-evm":     "neon",
	"neonevm":      "neon",
	"neon-mainnet": "neon",
	// CRO
	"cro":            "cro",
	"cronos":         "cro",
	"crypto.com":     "cro",
	"cronos-mainnet": "cro",
	// ALPH
	"alph":             "alph",
	"alephium":         "alph",
	"alephium-mainnet": "alph",
	// SUI
	"sui":         "sui",
	"sui-mainnet": "sui",
	// CORE
	"core":            "core",
	"coredao":         "core",
	"corechain":       "core",
	"core-dao":        "core",
	"core-blockchain": "core",
	"core-mainnet":    "core",
	// ASTR
	"astr":          "astr",
	"astar":         "astr",
	"astar-mainnet": "astr",
	// CHZ
	"chz":            "chz",
	"chiliz":         "chz",
	"chiliz-chain":   "chz",
	"chiliz-mainnet": "chz",
	// MADA
	"mada":              "mada",
	"milkomeda":         "mada",
	"milkomeda-cardano": "mada",
	"milkomeda-c1":      "mada",
	// BOB
	"bob":         "bob",
	"bob-mainnet": "bob",
	"bob-l2":      "bob",
	// MOVR
	"movr":              "movr",
	"moonriver":         "movr",
	"moonriver-mainnet": "movr",
	// XPL
	"xpl":          "xpl",
	"xpla":         "xpl",
	"xpla-mainnet": "xpl",
	// HYPE
	"hype":                "hype",
	"hyperliquid":         "hype",
	"hyperliquid-l1":      "hype",
	"hl":                  "hype",
	"hyperliquid-mainnet": "hype",
	// EVER
	"ever":              "ever",
	"everscale":         "ever",
	"everscale-mainnet": "ever",
	// UNI
	"uni":              "uni",
	"unichain":         "uni",
	"unichain-mainnet": "uni",
	// MNT
	"mnt":            "mnt",
	"mantle":         "mnt",
	"mantle-mainnet": "mnt",
	// VLX
	"vlx":           "vlx",
	"velas":         "vlx",
	"velas-mainnet": "vlx",
	// CYBER
	"cyber":         "cyber",
	"cyberconnect":  "cyber",
	"cyber-mainnet": "cyber",
	// FUSE
	"fuse":         "fuse",
	"fusenetwork":  "fuse",
	"fuse-mainnet": "fuse",
	// DUCK
	"duck":      "duck",
	"duckchain": "duck",
	// EOS
	"eos":         "eos",
	"eosio":       "eos",
	"eos-mainnet": "eos",
	// BASE
	"base":         "base",
	"base-mainnet": "base",
	"base-l2":      "base",
	// A8
	"a8":               "a8",
	"ancient8":         "a8",
	"ancient8-mainnet": "a8",
	// INJ
	"inj":               "inj",
	"injective":         "inj",
	"injective-mainnet": "inj",
	// KAVA
	"kava":         "kava",
	"kava-mainnet": "kava",
	// AVAX
	"avax":              "avax",
	"avalanche":         "avax",
	"avalanche-c":       "avax",
	"avalanche-c-chain": "avax",
	"avalanche-mainnet": "avax",
	// TT
	"tt":           "tt",
	"thundercore":  "tt",
	"thunder-core": "tt",
	"tt-mainnet":   "tt",
	// XTZ
	"xtz":           "xtz",
	"tezos":         "xtz",
	"tezos-mainnet": "xtz",
	// OPBNB
	"opbnb":         "opbnb",
	"op-bnb":        "opbnb",
	"optimism-bnb":  "opbnb",
	"opbnb-mainnet": "opbnb",
	// XLM
	"xlm":             "xlm",
	"stellar":         "xlm",
	"stellar-mainnet": "xlm",
	// BRISE
	"brise":           "brise",
	"bitgert":         "brise",
	"bitgert-mainnet": "brise",
	// XOR
	"xor":          "xor",
	"sora":         "xor",
	"sora-mainnet": "xor",
	// ONE
	"one":             "one",
	"harmony":         "one",
	"harmony-mainnet": "one",
	// NEAR
	"near":          "near",
	"near-protocol": "near",
	"near-mainnet":  "near",
	// BEAM
	"beam":         "beam",
	"beam-gaming":  "beam",
	"beamx":        "beam",
	"beam-mainnet": "beam",
	// BB
	"bb":                "bb",
	"bouncebit":         "bb",
	"bouncebit-mainnet": "bb",
	// KAI
	"kai":                 "kai",
	"kardiachain":         "kai",
	"kardia":              "kai",
	"kardiachain-mainnet": "kai",
	// SOL
	"sol":            "solana",
	"solana":         "solana",
	"solana-mainnet": "solana",
	// ZIL
	"zil":             "zil",
	"zilliqa":         "zil",
	"zilliqa-mainnet": "zil",
	// PLS
	"pls":                "pls",
	"pulse":              "pls",
	"pulsechain":         "pls",
	"pulsechain-mainnet": "pls",
	// ARBITRUM
	"arbitrum":         "arbitrum",
	"arb":              "arbitrum",
	"arbitrum-one":     "arbitrum",
	"arbitrum-nova":    "arbitrum",
	"arbi":             "arbitrum",
	"arbitrum-mainnet": "arbitrum",
	// NRG
	"nrg":            "nrg",
	"energi":         "nrg",
	"energi-mainnet": "nrg",
	// CFX
	"cfx":             "cfx",
	"conflux":         "cfx",
	"conflux-espace":  "cfx",
	"conflux-mainnet": "cfx",
	// BSC
	"bsc":                 "bsc",
	"bnb":                 "bsc",
	"binance":             "bsc",
	"binance-smart-chain": "bsc",
	"bnb-chain":           "bsc",
	"bnbchain":            "bsc",
	"bsc-mainnet":         "bsc",
	// HBAR
	"hbar":           "hbar",
	"hedera":         "hbar",
	"hedera-mainnet": "hbar",
	// TON
	"ton":              "ton",
	"the-open-network": "ton",
	"toncoin":          "ton",
	"ton-mainnet":      "ton",
	// CORN
	"corn":      "corn",
	"cornchain": "corn",
	// MTR
	"mtr":           "mtr",
	"meter":         "mtr",
	"meter-mainnet": "mtr",
	// APE
	"ape":         "ape",
	"apechain":    "ape",
	"ape-mainnet": "ape",
	// CANTO
	"canto":         "canto",
	"canto-mainnet": "canto",
	// HT
	"ht":              "ht",
	"heco":            "ht",
	"huobi-token":     "ht",
	"huobi-eco-chain": "ht",
	// FSN
	"fsn":            "fsn",
	"fusion":         "fsn",
	"fusion-mainnet": "fsn",
	// ICP
	"icp":               "icp",
	"internet-computer": "icp",
	"dfinity":           "icp",
	"ic":                "icp",
	"icp-mainnet":       "icp",
	// NO_CA
	"no_ca": "no_ca",
	// BLAST
	"blast":         "blast",
	"blast-mainnet": "blast",
	"blast-l2":      "blast",
	// DOGE
	"doge":      "doge",
	"dogecoin":  "doge",
	"dogechain": "doge",
	// GLMR
	"glmr":             "glmr",
	"moonbeam":         "glmr",
	"moonbeam-mainnet": "glmr",
	// WAVES
	"waves":         "waves",
	"waves-mainnet": "waves",
	// FTM
	"ftm":            "ftm",
	"fantom":         "ftm",
	"fantom-opera":   "ftm",
	"fantom-mainnet": "ftm",
	// ROSE
	"rose":           "rose",
	"oasis":          "rose",
	"oasis-emerald":  "rose",
	"oasis-sapphire": "rose",
	// TOMB
	"tomb":      "tomb",
	"tombchain": "tomb",
	// IOTA
	"iota":         "iota",
	"iota-mainnet": "iota",
	"shimmer":      "iota",
	// CELO
	"celo":         "celo",
	"celo-mainnet": "celo",
	// S
	"s":             "s",
	"sonic":         "s",
	"fantom-sonic":  "s",
	"sonic-mainnet": "s",
	// SC_TOKEN
	"sc_token": "sc_token",
	"sctoken":  "sc_token",
	// POLYGON
	"polygon":         "polygon",
	"matic":           "polygon",
	"polygon-pos":     "polygon",
	"poly":            "polygon",
	"polygon-mainnet": "polygon",
	// RBTC
	"rbtc":              "rbtc",
	"rsk":               "rbtc",
	"rootstock":         "rbtc",
	"rootstock-mainnet": "rbtc",
	// TRON
	"tron":         "tron",
	"trx":          "tron",
	"tron-mainnet": "tron",
	// KCS
	"kcs":                    "kcs",
	"kcc":                    "kcs",
	"kucoin-community-chain": "kcs",
	"kcc-mainnet":            "kcs",
	// KLAY
	"klay":           "klay",
	"klaytn":         "klay",
	"klaytn-mainnet": "klay",
}

// LookupChainName returns the canonical lowercase chain name for the provided alias.
// The lookup is case-insensitive and reports whether a match was found.
func LookupChainName(chain string) (string, bool) {
	if chain == "" {
		return "", false
	}

	canonical, ok := ChainAliasToName[strings.ToLower(chain)]
	return canonical, ok
}
